### ISSUE TITLE
Arduion_library_creation_guide/src/TestLib.cpp

### ISSUE THREAD

**Issue by MandoRick** [RefreshMyMind-I/Arduion_library_creation_guide#2]
[Arduion_library_creation_guide](https://github.com/RefreshMyMind-I/Arduion_library_creation_guide)/[src](https://github.com/RefreshMyMind-I/Arduion_library_creation_guide/tree/main/src)/TestLib.cpp

you have some stray semicolons (;)

**Comment by RefreshMyMind-I** [comment]
Removed, Thanks for feedback.
